The following notebook is baisc PyTorch Linear Algebra for review and notes

### Element wise operations

In [6]:
import torch
a = torch.tensor([[1], [2], [4], [8]])
b = torch.tensor([[1], [0.5], [0.25], [0.125]])

In [16]:
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(torch.dot(torch.tensor([1, 2]), torch.tensor([3, 4])))

tensor([[2.0000],
        [2.5000],
        [4.2500],
        [8.1250]])
tensor([[0.0000],
        [1.5000],
        [3.7500],
        [7.8750]])
tensor([[1.],
        [1.],
        [1.],
        [1.]])
tensor([[ 1.],
        [ 4.],
        [16.],
        [64.]])
tensor(11)


Sigmoid is used a lot in machine learning as it represnts a value between 0 sigmoid(-infinity) and 1 sigmoid(+infinity)
$$
    \sigma = \frac{1}{1+e^{-x}}
$$

In [9]:
print(torch.sigmoid(a))

tensor([[0.7311],
        [0.8808],
        [0.9820],
        [0.9997]])


ReLU (Rectified Linear Unit) is also used a lot in machine learning, if value < 0 then 0 and value > 0 then its the value itself. 

In [10]:
c = torch.tensor([4, -4, 0, 2])
print(torch.relu(c))

tensor([4, 0, 0, 2])


In [12]:
random_tensor = torch.rand((3, 4, 2)) # three dimensional tensor with random values
print(random_tensor) 
print(random_tensor.shape)

tensor([[[0.7204, 0.6914],
         [0.5328, 0.4590],
         [0.6924, 0.0677],
         [0.1331, 0.3136]],

        [[0.3598, 0.9800],
         [0.2434, 0.5260],
         [0.8095, 0.4079],
         [0.6437, 0.7622]],

        [[0.5389, 0.0035],
         [0.1880, 0.2451],
         [0.2731, 0.7007],
         [0.5499, 0.6288]]])
torch.Size([3, 4, 2])


The dot product of 2 vectors is the same as the the norm of the vectors times cos(theta):
$$
    |\vec{a}||\vec{b}|cos(\theta)
$$
This way we can express it geometrically

CLIP – Contrastive Language-Image Pretraining
a neural network with both language and vision (mutimodal model)

In [21]:
from transformers import CLIPProcessor, CLIPModel
model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

preprocessor_config.json:   0%|          | 0.00/316 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/592 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/862k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/525k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.22M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/389 [00:00<?, ?B/s]

In [25]:
import requests
from PIL import Image 
url = "http://images.cocodataset.org/val2017/000000039769.jpg"
image = Image.open(requests.get(url, stream=True).raw)
inputs = processor(images=image, return_tensors="pt")
image_features = model.get_image_features(**inputs)

print(image_features)

tensor([[-1.0570e-01,  1.3791e-01, -2.9612e-01,  2.1249e-02, -6.4068e-02,
         -1.6862e-01, -1.3515e-01, -2.4467e-03,  4.7376e-01, -1.7627e-01,
          2.4440e-01, -3.7972e-01,  4.8330e-02, -1.3981e-01, -3.4045e-01,
         -1.2676e-01, -2.3266e-01, -2.9760e-01,  1.7886e-01,  4.9609e-02,
         -1.3074e+00, -3.2436e-02,  4.2144e-01, -3.3363e-01, -4.7372e-02,
          2.9805e-01,  2.3910e-01, -1.8429e-01,  1.5669e-01, -4.8808e-02,
         -7.7587e-02,  2.5887e-01, -7.3552e-02,  1.7692e-01, -5.7918e-01,
         -4.9201e-03,  2.7906e-01, -2.8706e-01,  1.9080e-01,  3.2632e-01,
         -1.0051e-01, -3.4647e-01,  7.1681e-03, -1.4746e-01, -1.9010e-01,
          5.7778e-04,  5.2023e-01,  1.5117e-01, -9.1645e-02,  1.7595e-01,
          1.6325e-01,  2.5157e-01,  1.1609e-01, -5.3789e-02,  2.2871e-01,
          1.8608e-01,  2.5763e-01,  6.0314e-01, -2.5823e-01, -1.6781e-01,
          4.2385e-01, -1.3951e-01, -6.3744e-02,  3.5568e-01, -7.4245e-02,
         -2.7096e-01,  2.2417e-01,  1.

Vector databases are key for these embeddings
- support for euclidean distance, cosine similarity, and dot product
- scalability
- specialized indexing
- efficient similarity search

**Faiss** (Facebook Ai Similarity Search) is an optimization for the dot product used to compare other embeddings

In [12]:
from pinecone import Pinecone, ServerlessSpec
from dotenv import load_dotenv
import os

pc = Pinecone(api_key=os.getenv("PINECONE_API"))

ModuleNotFoundError: No module named 'langchain'